window.PLACES = {
  hkg: { name: "香港国际机场 T1", lat: 22.3080, lng: 113.9185 },
  pvg: { name: "上海浦东机场 T1", lat: 31.1443, lng: 121.8083 },
  schiphol: { name: "阿姆斯特丹史基浦机场", lat: 52.3105, lng: 4.7683 },
  ams_zuid: { name: "Amsterdam Zuid 站", lat: 52.3390, lng: 4.8730 },
  ams_hotel: { name: "Crowne Plaza Amsterdam South", lat: 52.3369, lng: 4.8736 },
  dam: { name: "水坝广场", lat: 52.3731, lng: 4.8926 },
  damrak: { name: "Damrak / 辛格花市一带", lat: 52.3702, lng: 4.8937 },
  vangogh: { name: "梵高博物馆", lat: 52.3584, lng: 4.8811 },
  rijks: { name: "荷兰国立博物馆", lat: 52.3600, lng: 4.8852 },
  museumplein: { name: "博物馆广场", lat: 52.3575, lng: 4.8818 },
  depijp: { name: "De Pijp / Albert Cuyp", lat: 52.3558, lng: 4.8952 },
  centraal: { name: "阿姆斯特丹中央车站", lat: 52.3789, lng: 4.9003 },
  zaandijk: { name: "Zaandijk Zaanse Schans 站", lat: 52.4692, lng: 4.8065 },
  zaanse: { name: "桑斯安斯风车村", lat: 52.4737, lng: 4.8165 },
  volendam: { name: "沃伦丹", lat: 52.4954, lng: 5.0746 },
  marken: { name: "马肯", lat: 52.4586, lng: 5.1022 },
  ninestr: { name: "九小街 / 约旦区", lat: 52.3708, lng: 4.8856 },
  antwerp_cs: { name: "安特卫普中央车站", lat: 51.2172, lng: 4.4212 },
  antwerp_cat: { name: "安特卫普圣母主教座堂", lat: 51.2204, lng: 4.4015 },
  antwerp_markt: { name: "安特卫普大广场", lat: 51.2211, lng: 4.3997 },
  grandplace: { name: "布鲁塞尔大广场", lat: 50.8467, lng: 4.3525 },
  manneken: { name: "撒尿小童", lat: 50.8450, lng: 4.3499 },
  galeries: { name: "圣休伯特皇家长廊", lat: 50.8478, lng: 4.3548 },
  stmichel: { name: "圣米歇尔大教堂", lat: 50.8478, lng: 4.3570 },
  montdesarts: { name: "艺术山", lat: 50.8436, lng: 4.3570 },
  bru_hotel: { name: "Rue de la Concorde 22 民宿", lat: 50.8283, lng: 4.3615 },
  atomium: { name: "原子球塔", lat: 50.8949, lng: 4.3416 },
  dinant: { name: "迪南城堡", lat: 50.2595, lng: 4.9127 },
  dinant_town: { name: "迪南圣母教堂 / 萨克斯桥", lat: 50.2612, lng: 4.9120 },
  namur: { name: "那慕尔城堡", lat: 50.4605, lng: 4.8607 },
  namur_old: { name: "那慕尔老城", lat: 50.4643, lng: 4.8675 },
  lux_bock: { name: "贝克要塞", lat: 49.6118, lng: 6.1365 },
  lux_center: { name: "卢森堡老城 / 大公宫", lat: 49.6116, lng: 6.1319 },
  lux_grund: { name: "Grund 谷底", lat: 49.6078, lng: 6.1360 },
  chantilly: { name: "香蒂伊城堡", lat: 49.1940, lng: 2.4858 },
  nord: { name: "巴黎北站", lat: 48.8809, lng: 2.3553 },
  par_hotel: { name: "73 Rue Saint Charles 民宿", lat: 48.8478, lng: 2.2863 },
  shakespeare: { name: "莎士比亚书店", lat: 48.8526, lng: 2.3471 },
  notredame: { name: "巴黎圣母院", lat: 48.8530, lng: 2.3499 },
  latin: { name: "拉丁区 / Mouffetard", lat: 48.8458, lng: 2.3496 },
  louvre: { name: "卢浮宫", lat: 48.8606, lng: 2.3376 },
  chapelle: { name: "圣礼拜堂", lat: 48.8554, lng: 2.3450 },
  arc: { name: "凯旋门", lat: 48.8738, lng: 2.2950 },
  champs: { name: "香榭丽舍大街", lat: 48.8690, lng: 2.3086 },
  trocadero: { name: "夏乐宫平台", lat: 48.8620, lng: 2.2875 },
  eiffel: { name: "埃菲尔铁塔 / 战神广场", lat: 48.8584, lng: 2.2945 },
  est: { name: "巴黎东站", lat: 48.8766, lng: 2.3593 },
  reims_st: { name: "兰斯站", lat: 49.2588, lng: 4.0242 },
  reims_cat: { name: "兰斯圣母大教堂", lat: 49.2539, lng: 4.0340 },
  reims_tau: { name: "塔宫", lat: 49.2532, lng: 4.0355 },
  champagne: { name: "香槟酒窖一带", lat: 49.2330, lng: 4.0550 },
  sacrecoeur: { name: "圣心大教堂", lat: 48.8867, lng: 2.3431 },
  tertre: { name: "小丘广场 / 爱墙", lat: 48.8865, lng: 2.3406 },
  javel: { name: "Javel 站", lat: 48.8465, lng: 2.2770 },
  versailles: { name: "凡尔赛宫", lat: 48.8049, lng: 2.1204 },
  trianon: { name: "特里亚农 / 王后农庄", lat: 48.8155, lng: 2.1040 },
  bastille: { name: "巴士底歌剧院", lat: 48.8520, lng: 2.3700 },
  stpancras: { name: "St Pancras International", lat: 51.5314, lng: -0.1261 },
  lon_hotel: { name: "10 Grenville Street 民宿", lat: 51.5234, lng: -0.1230 },
  trafalgar: { name: "特拉法加广场", lat: 51.5080, lng: -0.1281 },
  ngallery: { name: "英国国家美术馆", lat: 51.5089, lng: -0.1283 },
  whitehall: { name: "白厅 / 唐宁街", lat: 51.5036, lng: -0.1276 },
  bigben: { name: "大本钟 / 国会大厦", lat: 51.5007, lng: -0.1246 },
  abbey: { name: "威斯敏斯特教堂", lat: 51.4994, lng: -0.1276 },
  londoneye: { name: "伦敦眼 / 南岸", lat: 51.5033, lng: -0.1195 },
  british: { name: "大英博物馆", lat: 51.5194, lng: -0.1270 },
  bloomsbury: { name: "布鲁姆斯伯里", lat: 51.5218, lng: -0.1233 },
  towerbridge: { name: "伦敦塔桥", lat: 51.5055, lng: -0.0754 },
  tower: { name: "伦敦塔外观", lat: 51.5081, lng: -0.0759 },
  majesty: { name: "His Majesty's Theatre", lat: 51.5083, lng: -0.1319 },
  chinatown: { name: "中国城 / 苏豪", lat: 51.5116, lng: -0.1310 },
  stjames: { name: "圣詹姆斯公园", lat: 51.5020, lng: -0.1347 },
  buckingham: { name: "白金汉宫", lat: 51.5014, lng: -0.1419 },
  stpauls: { name: "圣保罗大教堂", lat: 51.5138, lng: -0.0984 },
  russell: { name: "Russell Square 站", lat: 51.5231, lng: -0.1244 },
  lhr: { name: "希思罗机场 T4", lat: 51.4597, lng: -0.4470 }
};

window.FLIGHTS = {
  hkg_pvg: { from: "hkg", to: "pvg", label: "HKG → PVG　FM3018", day: "0924", note: "2h35m" },
  pvg_ams: { from: "pvg", to: "schiphol", label: "PVG → AMS　MU209", day: "0925", note: "11h55m" },
  lhr_pvg: { from: "lhr", to: "pvg", label: "LHR → PVG　MU552", day: "1006", note: "11h20m" },
  pvg_hkg: { from: "pvg", to: "hkg", label: "PVG → HKG　MU723", day: "1007", note: "2h40m" }
};

window.CITY_LABELS = [
  { name: "阿姆斯特丹", lat: 52.372, lng: 4.900 },
  { name: "安特卫普", lat: 51.221, lng: 4.430 },
  { name: "布鲁塞尔", lat: 50.850, lng: 4.380 },
  { name: "迪南", lat: 50.260, lng: 4.950 },
  { name: "卢森堡", lat: 49.612, lng: 6.160 },
  { name: "巴黎", lat: 48.856, lng: 2.370 },
  { name: "兰斯", lat: 49.258, lng: 4.060 },
  { name: "伦敦", lat: 51.507, lng: -0.105 }
];

window.STAYS = [
  { id: "ams_hotel", city: "阿姆斯特丹", nights: "9.25–9.27　3 晚" },
  { id: "bru_hotel", city: "布鲁塞尔", nights: "9.28–9.29　2 晚" },
  { id: "par_hotel", city: "巴黎 15 区", nights: "9.30–10.3　4 晚" },
  { id: "lon_hotel", city: "伦敦 Bloomsbury", nights: "10.4–10.5　2 晚" }
];

window.TRIP = {
  defaultDay: "0925",
  defaultVariant: "B",
  days: [
    {
      id: "0924",
      date: "9.24",
      weekday: "周四",
      city: "香港出发",
      region: "air",
      stay: "机上 / 浦东",
      theme: "香港国际机场起飞",
      summary: "22:05 FM3018 飞上海。当日路程在左下角世界航线图。",
      insetMode: "asia",
      worldFlights: ["hkg_pvg"],
      overviewFocus: ["hkg"],
      insetPlaces: ["hkg", "pvg"],
      overviewLegs: [],
      activities: [
        { time: "19:00", name: "抵达香港国际机场 T1 值机", place: "hkg", mode: "walk", note: "行李只挂到上海，不能直挂阿姆斯特丹" },
        { time: "22:05", name: "FM3018 起飞前往浦东", place: "pvg", mode: "flight", booked: true, note: "2h35m · 经济舱" }
      ]
    },
    {
      id: "0925",
      date: "9.25",
      weekday: "周五",
      city: "抵达阿姆斯特丹",
      region: "ams",
      stay: "阿姆斯特丹",
      theme: "浦东中转 + 水坝广场",
      summary: "14:55 抵达史基浦，火车至 Zuidas 入住，晚间只做散步式的水坝广场。",
      insetMode: "city",
      worldFlights: ["pvg_ams"],
      insetPlaces: ["schiphol", "ams_zuid", "ams_hotel", "dam", "damrak"],
      overviewLegs: [{ route: "schiphol_zuid" }],
      activities: [
        { time: "00:40", name: "抵达浦东 T1，提取行李过夜", place: "pvg", mode: "flight", booked: true, note: "中转 8h20m，须重新托运" },
        { time: "09:00", name: "MU209 起飞", place: "pvg", mode: "flight", booked: true, note: "11h55m" },
        { time: "14:55", name: "抵达史基浦机场", place: "schiphol", mode: "flight", booked: true },
        { time: "16:10", name: "NS 火车前往 Amsterdam Zuid", place: "ams_zuid", mode: "rail", route: "schiphol_zuid", note: "6–8 分钟 · €3.4" },
        { time: "16:40", name: "入住 Crowne Plaza Amsterdam South", place: "ams_hotel", mode: "stay", booked: true, note: "步行 8–10 分钟" },
        { time: "18:00", name: "水坝广场：王宫、新教堂、国家纪念碑", place: "dam", mode: "metro", note: "地铁 52 号线 Zuid → Rokin" },
        { time: "20:15", name: "Damrak 与运河区夜景散步", place: "damrak", mode: "walk", note: "日落约 19:33" },
        { time: "21:30", name: "返回酒店", place: "ams_hotel", mode: "metro" }
      ]
    },
    {
      id: "0926",
      date: "9.26",
      weekday: "周六",
      city: "阿姆斯特丹",
      region: "ams",
      stay: "阿姆斯特丹",
      theme: "梵高博物馆 + 国立博物馆",
      summary: "博物馆广场双馆，下午运河游船，晚餐在 De Pijp。",
      insetMode: "city",
      insetPlaces: ["ams_hotel", "vangogh", "rijks", "museumplein", "depijp"],
      overviewLegs: [],
      activities: [
        { time: "08:45", name: "前往博物馆广场", place: "museumplein", mode: "taxi", note: "建议打车 10 分钟，赶 09:15 时段" },
        { time: "09:15", name: "梵高博物馆", place: "vangogh", mode: "walk", booked: true, note: "已订 09:15 时段票 · 约 2.5 小时" },
        { time: "11:45", name: "博物馆广场草坪休息，可选 Moco", place: "museumplein", mode: "walk" },
        { time: "14:00", name: "荷兰国立博物馆", place: "rijks", mode: "walk", booked: true, note: "已订 14:00 · 闭馆 17:00" },
        { time: "17:30", name: "运河游船（Stromma 码头）", place: "rijks", mode: "ferry", note: "1 小时 · €20/人，尚未预订" },
        { time: "18:45", name: "De Pijp 区晚餐", place: "depijp", mode: "metro", note: "Albert Cuyp 市场周边" },
        { time: "20:30", name: "返回酒店", place: "ams_hotel", mode: "metro" }
      ]
    },
    {
      id: "0927",
      date: "9.27",
      weekday: "周日",
      city: "北荷兰水乡",
      region: "ams",
      stay: "阿姆斯特丹",
      theme: "风车村 + 沃伦丹 + 马肯环线",
      summary: "顺时针乡村环线，不走回头路。当日票建议 Amsterdam & Region Travel Ticket €23。",
      insetMode: "region",
      insetPlaces: ["centraal", "zaanse", "volendam", "marken", "ninestr"],
      overviewLegs: [
        { route: "centraal_zaandijk" },
        { route: "zaanse_volendam" },
        { route: "volendam_marken" },
        { route: "marken_centraal" }
      ],
      activities: [
        { time: "08:20", name: "前往阿姆斯特丹中央车站", place: "centraal", mode: "metro", note: "Zuid 地铁 52 号线，约 20 分钟" },
        { time: "09:08", name: "NS 火车至 Zaandijk Zaanse Schans", place: "zaandijk", mode: "rail", route: "centraal_zaandijk", note: "17 分钟" },
        { time: "09:45", name: "桑斯安斯风车村", place: "zaanse", mode: "walk", note: "进村免费，风车内部 €5–6/座" },
        { time: "13:10", name: "EBS 801 路前往沃伦丹", place: "volendam", mode: "rail", route: "zaanse_volendam", note: "巴士约 60 分钟" },
        { time: "14:10", name: "沃伦丹渔港与彩色木屋", place: "volendam", mode: "walk" },
        { time: "16:00", name: "Marken Express 渡轮", place: "marken", mode: "ferry", route: "volendam_marken", note: "30 分钟 · €12.5，通票不含" },
        { time: "16:30", name: "马肯高脚木屋与灯塔", place: "marken", mode: "walk" },
        { time: "17:50", name: "EBS 315 路返回中央车站", place: "centraal", mode: "rail", route: "marken_centraal", note: "巴士 45 分钟" },
        { time: "19:00", name: "约旦区晚餐 + 九小街夜景", place: "ninestr", mode: "walk", note: "日落约 19:29" },
        { time: "21:15", name: "回酒店，收拾次日自驾行李", place: "ams_hotel", mode: "metro" }
      ]
    },
    {
      id: "0928",
      date: "9.28",
      weekday: "周一",
      city: "安特卫普 / 布鲁塞尔",
      region: "bru",
      stay: "布鲁塞尔",
      theme: "取车 + 安特卫普中停 + 布鲁塞尔老城",
      summary: "08:30 史基浦取车，A4/E19 南下。民宿 16:00 后入住，先停市中心逛老城。",
      insetMode: "region",
      insetPlaces: ["schiphol", "antwerp_cs", "antwerp_markt", "grandplace", "bru_hotel"],
      overviewLegs: [{ route: "ams_antwerp" }, { route: "antwerp_brussels" }],
      activities: [
        { time: "08:30", name: "史基浦取车", place: "schiphol", mode: "drive", booked: true, note: "Schiphol Plaza Aankomstpassage 22" },
        { time: "11:05", name: "抵达安特卫普", place: "antwerp_cs", mode: "drive", route: "ams_antwerp", note: "160 km / 1h50m" },
        { time: "11:20", name: "中央车站 + 圣母主教座堂", place: "antwerp_cat", mode: "walk", note: "馆内有鲁本斯《下十字架》" },
        { time: "12:30", name: "大广场与午餐", place: "antwerp_markt", mode: "walk" },
        { time: "14:30", name: "抵达布鲁塞尔大广场", place: "grandplace", mode: "drive", route: "antwerp_brussels", note: "50 km / 45m · 车停 Interparking" },
        { time: "15:30", name: "撒尿小童", place: "manneken", mode: "walk" },
        { time: "15:50", name: "圣休伯特皇家长廊", place: "galeries", mode: "walk" },
        { time: "16:30", name: "圣米歇尔大教堂", place: "stmichel", mode: "walk", note: "18:00 关门，17:15 前入内" },
        { time: "17:15", name: "艺术山观景台", place: "montdesarts", mode: "walk" },
        { time: "18:20", name: "Ixelles 民宿入住", place: "bru_hotel", mode: "stay", booked: true, note: "Rue de la Concorde 22" },
        { time: "19:15", name: "Ixelles 晚餐", place: "bru_hotel", mode: "walk" },
        { time: "21:00", name: "可选：原子球塔夜景", place: "atomium", mode: "drive", note: "自驾约 20 分钟；也可留到 9.29 B 版" }
      ]
    },
    {
      id: "0929",
      date: "9.29",
      weekday: "周二",
      city: "比利时南部",
      region: "bru",
      stay: "布鲁塞尔",
      theme: "迪南城堡一日游",
      hasVariant: true,
      variants: {
        B: {
          theme: "B 版：迪南 + 那慕尔",
          summary: "全天驾驶约 3 小时 / 195 km。能把迪南逛透，傍晚顺路补原子球塔。",
          insetPlaces: ["bru_hotel", "dinant", "namur", "atomium"],
          overviewLegs: [
            { route: "brussels_dinant" },
            { route: "dinant_namur" },
            { route: "namur_atomium" },
            { route: "atomium_brussels" }
          ],
          activities: [
            { time: "08:30", name: "出发前往迪南", place: "bru_hotel", mode: "drive" },
            { time: "10:00", name: "迪南城堡（含缆车）", place: "dinant", mode: "drive", route: "brussels_dinant", note: "1h30m / 100 km · €12" },
            { time: "11:00", name: "圣母教堂、萨克斯铜像与彩桥", place: "dinant_town", mode: "walk" },
            { time: "14:00", name: "那慕尔城堡", place: "namur", mode: "drive", route: "dinant_namur", note: "30 分钟 / 30 km" },
            { time: "15:30", name: "那慕尔老城与河畔", place: "namur_old", mode: "walk" },
            { time: "18:00", name: "顺路原子球塔", place: "atomium", mode: "drive", route: "namur_atomium" },
            { time: "19:30", name: "返回民宿晚餐", place: "bru_hotel", mode: "drive", route: "atomium_brussels", note: "当晚装好行李、比利时境内加满油" }
          ]
        },
        A: {
          theme: "A 版：迪南 + 卢森堡市",
          summary: "全天驾驶约 5 小时 / 440 km。卢森堡停留约 3 小时，21:30 回布鲁塞尔。",
          insetPlaces: ["bru_hotel", "dinant", "lux_center", "lux_bock"],
          overviewLegs: [
            { route: "brussels_dinant" },
            { route: "dinant_luxembourg" },
            { route: "luxembourg_brussels" }
          ],
          activities: [
            { time: "07:30", name: "出发前往迪南", place: "bru_hotel", mode: "drive" },
            { time: "09:30", name: "迪南城堡", place: "dinant", mode: "drive", route: "brussels_dinant", note: "1h30m / 100 km" },
            { time: "11:00", name: "圣母教堂与萨克斯桥", place: "dinant_town", mode: "walk" },
            { time: "14:30", name: "抵达卢森堡市", place: "lux_center", mode: "drive", route: "dinant_luxembourg", note: "1h20m / 120 km" },
            { time: "14:45", name: "贝克要塞地道", place: "lux_bock", mode: "walk", note: "UNESCO · €8" },
            { time: "16:30", name: "大公宫、圣母主教座堂", place: "lux_center", mode: "walk" },
            { time: "17:15", name: "下城 Grund", place: "lux_grund", mode: "walk" },
            { time: "21:30", name: "返回布鲁塞尔", place: "bru_hotel", mode: "drive", route: "luxembourg_brussels", note: "2h15m / 220 km" }
          ]
        }
      }
    },
    {
      id: "0930",
      date: "9.30",
      weekday: "周三",
      city: "香蒂伊 / 巴黎",
      region: "par",
      stay: "巴黎",
      theme: "还车日 + 圣母院登顶",
      summary: "E19/A2/A1 至香蒂伊，15:15 北站地下还车，18:45 已锁定登顶票。",
      insetMode: "region",
      insetPlaces: ["bru_hotel", "chantilly", "nord", "par_hotel", "notredame"],
      overviewLegs: [{ route: "brussels_chantilly" }, { route: "chantilly_nord" }],
      activities: [
        { time: "07:45", name: "比利时境内加满油后出发", place: "bru_hotel", mode: "drive", note: "R0 → E19 → A2 → A1" },
        { time: "10:45", name: "香蒂伊城堡与大马厩", place: "chantilly", mode: "drive", route: "brussels_chantilly", note: "255 km / 2h40m · 联票约 €18" },
        { time: "15:15", name: "巴黎北站地下 Level -5 还车", place: "nord", mode: "drive", route: "chantilly_nord", booked: true, note: "50 km · 之后全程公共交通" },
        { time: "16:40", name: "入住 15 区民宿", place: "par_hotel", mode: "stay", booked: true, note: "RER B + RER C 至 Javel，约 35 分钟" },
        { time: "17:35", name: "莎士比亚书店、新桥、圣母院立面", place: "shakespeare", mode: "metro" },
        { time: "18:45", name: "巴黎圣母院登顶", place: "notredame", mode: "walk", booked: true, note: "已订 18:45 塔楼票 · 424 级 · 日落 19:29" },
        { time: "19:50", name: "拉丁区晚餐", place: "latin", mode: "walk" },
        { time: "21:30", name: "返回 15 区", place: "par_hotel", mode: "metro" }
      ]
    },
    {
      id: "1001",
      date: "10.1",
      weekday: "周四",
      city: "巴黎",
      region: "par",
      stay: "巴黎",
      theme: "卢浮宫 + 西岱岛 + 凯旋门 + 铁塔",
      summary: "巴黎最满的一天，全部地铁短程衔接，终点铁塔步行 22 分钟回住处。",
      insetMode: "city",
      insetPlaces: ["par_hotel", "louvre", "chapelle", "notredame", "arc", "trocadero", "eiffel"],
      overviewLegs: [],
      activities: [
        { time: "09:30", name: "卢浮宫", place: "louvre", mode: "metro", booked: true, note: "已订 09:30 · 约 3.5 小时" },
        { time: "14:40", name: "圣礼拜堂", place: "chapelle", mode: "walk", note: "上层彩窗 · 10 月 17:00 闭馆" },
        { time: "16:00", name: "巴黎圣母院内部参观", place: "notredame", mode: "walk", note: "免费，官方 App 提前 2 天预约" },
        { time: "18:00", name: "凯旋门登顶", place: "arc", mode: "metro", note: "284 级 · 俯瞰星形广场" },
        { time: "18:50", name: "香榭丽舍大街下行", place: "champs", mode: "walk" },
        { time: "19:25", name: "夏乐宫平台拍铁塔", place: "trocadero", mode: "metro", note: "日落约 19:27" },
        { time: "20:00", name: "埃菲尔铁塔整点亮灯", place: "eiffel", mode: "walk" },
        { time: "20:15", name: "登铁塔（顶层或二层）", place: "eiffel", mode: "walk", note: "顶层票待抢 · 之后步行回 15 区" }
      ]
    },
    {
      id: "1002",
      date: "10.2",
      weekday: "周五",
      city: "兰斯 / 蒙马特",
      region: "par",
      stay: "巴黎",
      theme: "兰斯往返 + 圣心日落",
      summary: "TGV 46 分钟到兰斯；回程东站距蒙马特两站地铁，接日落。",
      insetMode: "region",
      insetPlaces: ["par_hotel", "est", "reims_cat", "champagne", "sacrecoeur"],
      overviewLegs: [{ route: "paris_reims" }],
      activities: [
        { time: "07:30", name: "前往巴黎东站", place: "est", mode: "metro", note: "10 号线换 4 号线，约 35 分钟" },
        { time: "08:30", name: "TGV inOui 前往兰斯", place: "reims_st", mode: "rail", route: "paris_reims", note: "直达 46 分钟" },
        { time: "09:40", name: "兰斯圣母大教堂", place: "reims_cat", mode: "walk", note: "加冕地 · UNESCO · 免费" },
        { time: "11:15", name: "塔宫", place: "reims_tau", mode: "walk" },
        { time: "14:00", name: "香槟酒窖参观 + 品鉴", place: "champagne", mode: "walk", note: "须预约：凯歌 / 泰亭哲 / 巴黎之花" },
        { time: "17:30", name: "TGV 返回巴黎东站", place: "est", mode: "rail", note: "46 分钟" },
        { time: "19:10", name: "圣心大教堂与全景台阶", place: "sacrecoeur", mode: "metro", note: "日落约 19:25 · 穹顶已关闭" },
        { time: "20:00", name: "小丘广场、爱墙", place: "tertre", mode: "walk" },
        { time: "22:00", name: "返回 15 区", place: "par_hotel", mode: "metro" }
      ]
    },
    {
      id: "1003",
      date: "10.3",
      weekday: "周六",
      city: "凡尔赛 / 巴士底",
      region: "par",
      stay: "巴黎",
      theme: "凡尔赛宫 +《哈姆雷特》",
      summary: "必须 15:10 前离园。晚上 19:30 巴士底歌剧，8 号线 Commerce 直达。",
      insetMode: "region",
      insetPlaces: ["par_hotel", "javel", "versailles", "trianon", "bastille"],
      overviewLegs: [{ route: "javel_versailles" }],
      activities: [
        { time: "08:00", name: "RER C Javel 直达凡尔赛", place: "javel", mode: "rail", note: "坐终点 Versailles Château Rive Gauche 的班次" },
        { time: "09:00", name: "凡尔赛宫殿主体 / 镜厅", place: "versailles", mode: "rail", route: "javel_versailles", note: "建议 €32 Passeport 通票" },
        { time: "11:00", name: "花园与大喷泉音乐秀", place: "versailles", mode: "walk" },
        { time: "13:30", name: "大小特里亚农 + 王后农庄", place: "trianon", mode: "walk" },
        { time: "15:10", name: "离开凡尔赛，回住处换衣", place: "par_hotel", mode: "rail" },
        { time: "17:50", name: "抵达巴士底广场，早晚餐", place: "bastille", mode: "metro", note: "8 号线直达" },
        { time: "19:30", name: "《哈姆雷特》Hamlet", place: "bastille", mode: "walk", booked: true, note: "已订 · 3h40m · 约 23:10 散场" }
      ]
    },
    {
      id: "1004",
      date: "10.4",
      weekday: "周日",
      city: "巴黎 → 伦敦",
      region: "lon",
      stay: "伦敦",
      theme: "欧洲之星 + 西敏南岸",
      summary: "09:40 欧洲之星已订。放大图看伦敦下午步行；跨海铁路见总览红线。",
      insetMode: "city",
      worldFlights: [],
      insetPlaces: ["stpancras", "lon_hotel", "trafalgar", "bigben", "abbey", "londoneye"],
      overviewLegs: [{ route: "eurostar" }],
      activities: [
        { time: "07:00", name: "退房前往巴黎北站", place: "nord", mode: "taxi", note: "带大箱子建议打车 25 分钟" },
        { time: "07:40", name: "北站办理申根退税 + 值机边检", place: "nord", mode: "walk", note: "离开申根区的唯一退税窗口" },
        { time: "09:40", name: "欧洲之星发车", place: "stpancras", mode: "rail", route: "eurostar", booked: true, note: "2h16m · 10:56 到（伦敦时间）" },
        { time: "11:15", name: "民宿放行李（15:00 后入住）", place: "lon_hotel", mode: "stay", booked: true, note: "步行 15 分钟 · 须提前约寄存" },
        { time: "13:20", name: "特拉法加广场", place: "trafalgar", mode: "metro" },
        { time: "13:45", name: "英国国家美术馆", place: "ngallery", mode: "walk", note: "免费无需预约" },
        { time: "15:45", name: "白厅、唐宁街外观", place: "whitehall", mode: "walk" },
        { time: "16:15", name: "国会大厦 + 大本钟外观", place: "bigben", mode: "walk" },
        { time: "16:45", name: "威斯敏斯特教堂外观", place: "abbey", mode: "walk", note: "周日不接待游客，正式参观在 10.6" },
        { time: "17:00", name: "南岸与伦敦眼，隔河拍夜景", place: "londoneye", mode: "walk", note: "日落约 18:29" },
        { time: "20:30", name: "返回民宿正式入住", place: "lon_hotel", mode: "metro" }
      ]
    },
    {
      id: "1005",
      date: "10.5",
      weekday: "周一",
      city: "伦敦",
      region: "lon",
      stay: "伦敦",
      theme: "大英博物馆 + 塔桥 +《歌剧魅影》",
      summary: "10:20 大英已订。17:15 前结束塔桥，赶 19:30 西区演出。",
      insetMode: "city",
      insetPlaces: ["lon_hotel", "british", "towerbridge", "tower", "majesty"],
      overviewLegs: [],
      activities: [
        { time: "09:15", name: "布鲁姆斯伯里街区散步", place: "bloomsbury", mode: "walk" },
        { time: "10:20", name: "大英博物馆", place: "british", mode: "walk", booked: true, note: "已订免费时段 · 约 3 小时" },
        { time: "15:10", name: "伦敦塔桥展览（玻璃步道）", place: "towerbridge", mode: "metro", note: "10 月起 16:30 末次入场" },
        { time: "16:30", name: "伦敦塔外观与河畔", place: "tower", mode: "walk" },
        { time: "17:45", name: "中国城 / 苏豪早晚餐", place: "chinatown", mode: "metro" },
        { time: "19:30", name: "《歌剧魅影》", place: "majesty", mode: "walk", booked: true, note: "His Majesty's Theatre · 约 22:00 散场" }
      ]
    },
    {
      id: "1006",
      date: "10.6",
      weekday: "周二",
      city: "伦敦返程",
      region: "lon",
      stay: "机上",
      theme: "两座教堂 + 希思罗起飞",
      summary: "上午威斯敏斯特、下午圣保罗登穹顶，17:10 皮卡迪利线直达 T4。",
      insetMode: "region",
      worldFlights: ["lhr_pvg"],
      insetPlaces: ["abbey", "buckingham", "stpauls", "russell", "lhr"],
      overviewLegs: [{ route: "russell_lhr" }],
      activities: [
        { time: "07:45", name: "退房，行李暂存民宿", place: "lon_hotel", mode: "stay" },
        { time: "09:00", name: "议会广场，大本钟近观", place: "bigben", mode: "metro" },
        { time: "09:30", name: "威斯敏斯特教堂", place: "abbey", mode: "walk", note: "周二 09:30 开门 · £30 含语音导览" },
        { time: "12:00", name: "圣詹姆斯公园穿行 + 白金汉宫外观", place: "buckingham", mode: "walk" },
        { time: "14:00", name: "圣保罗大教堂 + 登穹顶", place: "stpauls", mode: "metro", note: "16:00 停止入场 · 金廊 528 级" },
        { time: "16:40", name: "回民宿取行李", place: "lon_hotel", mode: "metro" },
        { time: "17:10", name: "皮卡迪利线直达希思罗 T4", place: "lhr", mode: "rail", route: "russell_lhr", note: "55–60 分钟 · 确认终点是 Terminal 4" },
        { time: "21:20", name: "MU552 起飞回国", place: "lhr", mode: "flight", booked: true, note: "11h20m" }
      ]
    },
    {
      id: "1007",
      date: "10.7",
      weekday: "周三",
      city: "抵港",
      region: "air",
      stay: "—",
      theme: "浦东中转 + 返回香港",
      summary: "行李直挂香港。当日路程在左下角世界航线图。",
      insetMode: "asia",
      worldFlights: ["pvg_hkg"],
      insetPlaces: ["pvg", "hkg"],
      overviewLegs: [],
      activities: [
        { time: "15:40", name: "抵达浦东 T1，走国际中转", place: "pvg", mode: "flight", booked: true, note: "行李已直挂，无需提取" },
        { time: "18:25", name: "MU723 起飞", place: "pvg", mode: "flight", booked: true, note: "2h40m" },
        { time: "21:05", name: "抵达香港国际机场 T1", place: "hkg", mode: "flight", booked: true }
      ]
    }
  ]
};
